name: Test API
on: [push]
env: 
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
    # Run tests
    test:
        name: Test 
        runs-on: ubuntu-latest
        services:
            mongo:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: rootuser
                    MONGO_INITDB_ROOT_PASSWORD: rootpass
                ports:
                    - 27017:27017
        steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 18
            uses: actions/setup-java@v3
            with:
              java-version: '18'
              distribution: 'temurin'
          - name: Test with Maven
            run: cd api && mvn test
