name: Test API
on: [push]
env:
  APP_MONGO_USER: rootuser 
  APP_MONGO_PASS: rootpass 
  APP_MONGO_DB: ironinstruction 
jobs:
    # Run tests
    test:
        name: Test 
        runs-on: ubuntu-latest
        services:
            mongo:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_USER}
                    MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_PASS}
                    MONGO_INITDB_DATABASE: ${APP_MONGO_DB}
                options: >-
                    --health-cmd mongo
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 27017:27017
        steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 17
            uses: actions/setup-java@v2
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Test with Maven
            run: mvn test
